# Generated by Django 2.0.4 on 2018-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='nickname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
