# Generated by Django 2.0.4 on 2018-06-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0002_normaluser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='nickname',
        ),
    ]
