# Generated by Django 2.0.4 on 2018-06-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0004_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userId',
            new_name='user',
        ),
    ]
